@ECHO OFF

java.exe -jar bagger-2.1.2.jar -Xms512m -classpath spring-beans-2.5.1.jar;bagger-2.1.2.jar

IF %ERRORLEVEL% GTR 0 GOTO MSG
GOTO END

:MSG
ECHO.
ECHO.
ECHO PLEASE CHECK IF JAVA 1.6 IS INSTALLED OR IT IS IN THE SYSTEM PATH
ECHO.
ECHO TO SET JAVA FOR THE BAGGER APPLICATION PLEASE LOOK AT SECTION '5' IN THE INCLUDED README.TXT FILE
ECHO.
PAUSE

:END
