PREFIX=
DATABASE=package_modeler

## ROLES
ADMIN=transfer_fixture_writer_user
READER=transfer_reader_user
WRITER=transfer_data_writer_user

## OWNERS
ADMIN_OWNER=package_modeler_fixture_writer_role
READER_OWNER=package_modeler_reader_role
WRITER_OWNER=package_modeler_data_writer_role

.PHONY: reset core-database core-fixtures \
	    ndnp-database ndnp-fixtures \
		transport-database transport-fixtures

database: reset core-database core-fixtures \
	    ndnp-database ndnp-fixtures \
		transport-database transport-fixtures

##----------------------------------------------------------------------

reset:
	## Removing existing database
	-@dropdb $(PREFIX)$(DATABASE)
	-@echo "drop role $(PREFIX)$(ADMIN);" | psql
	-@echo "drop role $(PREFIX)$(READER);" | psql
	-@echo "drop role $(PREFIX)$(WRITER);" | psql
	-@echo "drop role $(PREFIX)$(ADMIN_OWNER);" | psql
	-@echo "drop role $(PREFIX)$(READER_OWNER);" | psql
	-@echo "drop role $(PREFIX)$(WRITER_OWNER);" | psql

##----------------------------------------------------------------------

## See https://rdc.lctl.gov/trac/transfer/wiki/TransferCoreDeployment
core-database:
	## Prepopulate core roles
	@echo "CREATE ROLE $(PREFIX)$(ADMIN) \
		WITH PASSWORD '$(PREFIX)$(ADMIN)' \
		NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE LOGIN;" | psql
	@echo "CREATE ROLE $(PREFIX)$(READER) \
		WITH PASSWORD '$(PREFIX)$(READER)' \
		NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE LOGIN;" | psql
	@echo "CREATE ROLE $(PREFIX)$(WRITER) \
		WITH PASSWORD '$(PREFIX)$(WRITER)' \
		NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE LOGIN;" | psql
	
	## Create the database
	@echo "CREATE DATABASE $(PREFIX)$(DATABASE) ENCODING = 'UTF8';" | psql
	
	## Load the DDL and set permissions
	@psql $(PREFIX)$(DATABASE) < ../transfer/db/inventory-core.sql
	@sed -e 's/$(ADMIN_OWNER)/$(PREFIX)$(ADMIN_OWNER)/g;\
			s/$(READER_OWNER)/$(PREFIX)$(READER_OWNER)/g;\
			s/$(WRITER_OWNER)/$(PREFIX)$(WRITER_OWNER)/g' \
			../transfer/db/inventory-core.permissions.sql | psql $(PREFIX)$(DATABASE)
	
	## Add associations between users and roles
	@echo "GRANT $(PREFIX)$(ADMIN_OWNER) TO $(PREFIX)$(ADMIN);" | psql
	@echo "GRANT $(PREFIX)$(READER_OWNER) TO $(PREFIX)$(READER);" | psql
	@echo "GRANT $(PREFIX)$(WRITER_OWNER) TO $(PREFIX)$(WRITER);" | psql

## See https://rdc.lctl.gov/trac/transfer/wiki/Version1.0ReleaseNotes
## NOTE: The Java config files must be updated to point to 
##       the database we just created
core-fixtures:
	## Adding Core Inventory Fixtures
	@fixturedriver createrepository -id ndiipp
	@fixturedriver createrole -id storage_system
	@fixturedriver createsystem -id sun9 -roles storage_system
	@fixturedriver createsystem -id rs25 -roles storage_system
	@fixturedriver createperson -id scott -firstname Scott -surname Phelps
	@fixturedriver createsoftware -id packagemodeler-core-1.0
	@fixturedriver createsoftware -id md5deep-2.0.1

##----------------------------------------------------------------------

## See https://rdc.lctl.gov/trac/transfer/wiki/TransferCoreDeployment#NDNP
ndnp-database:
	@psql $(PREFIX)$(DATABASE) < ../transfer/db/inventory-ndnp.sql
	@sed -e 's/$(ADMIN_OWNER)/$(PREFIX)$(ADMIN_OWNER)/g;\
			s/$(READER_OWNER)/$(PREFIX)$(READER_OWNER)/g;\
			s/$(WRITER_OWNER)/$(PREFIX)$(WRITER_OWNER)/g' \
			../transfer/db/inventory-ndnp.permissions.sql | psql $(PREFIX)$(DATABASE)

## See https://rdc.lctl.gov/trac/ndnptransfer/wiki/NTVersion1.0ReleaseNotes
## NOTE: The Java config files must be updated to point to 
##       the database we just created
ndnp-fixtures:
	## Adding NDNP Inventory Fixtures
	@fixturedriver createrepository -id ndnp
	@fixturedriver createperson -id ray -firstname Ray -surname Murray
	@fixturedriver createperson -id myron -firstname Myron -surname Briggs
	@fixturedriver createperson -id scott -firstname Scott -surname Phelps
	@fixturedriver createsystem -id rdc-workflow
	@fixturedriver createrole -id ndnp_awardee
	@fixturedriver createorganization -id CU-Riv -name "University of California, Riverside" -roles ndnp_awardee
	@fixturedriver createorganization -id FUG -name "University of Florida Libraries, Gainesville" -roles ndnp_awardee
	@fixturedriver createorganization -id KyU -name "University of Kentucky Libraries, Lexington" -roles ndnp_awardee
	@fixturedriver createorganization -id NN -name "New York Public Library, New York City" -roles ndnp_awardee
	@fixturedriver createorganization -id UUML -name "University of Utah, Salt Lake City" -roles ndnp_awardee
	@fixturedriver createorganization -id VIC -name "Library of Virginia, Richmond" -roles ndnp_awardee
	@fixturedriver createorganization -id DLC -name "Library of Congress" -roles ndnp_awardee
	@fixturedriver createorganization -id MnHi -name "Minnesota Historical Society" -roles ndnp_awardee
	@fixturedriver createorganization -id NbU -name "University of Nebraska, Lincoln" -roles ndnp_awardee
	@fixturedriver createorganization -id TxDN -name "University of North Texas, Denton" -roles ndnp_awardee
	

##----------------------------------------------------------------------

transport-database:
	## Creating Transport Schema
	@psql $(PREFIX)$(DATABASE) < ../transfer/db/transport.sql
	@sed -e 's/$(ADMIN_OWNER)/$(PREFIX)$(ADMIN_OWNER)/g;\
			s/$(READER_OWNER)/$(PREFIX)$(READER_OWNER)/g;\
			s/$(WRITER_OWNER)/$(PREFIX)$(WRITER_OWNER)/g' \
			../transfer/db/transport.permissions.sql | psql $(PREFIX)$(DATABASE)

## NOTE: The Java *and Perl* config files must be updated to point to 
##       the database we just created.
transport-fixtures:
	## Adding Transport Inventory Fixtures
	@fixturedriver createrepository -id test
	@fixturedriver createsystem -id localhost -roles storage_system
	@fixturedriver createsoftware -id transport-1.0
	## Adding Transport Fixtures
	@transport-add-system -name localhost -host localhost
	@transport-add-user   -user $(USER)   -real 'Transport Tester'

##----------------------------------------------------------------------

