package gov.loc.repository.transfer.ui.reports;

import gov.loc.repository.transfer.ui.models.Report;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import org.springframework.stereotype.Component;
/**
 * <<Class summary>>
 *
 * @author Chris Thatcher &lt;&gt;
 * @version $Rev$
 */
@Component
public class CoreReport01 extends Report {
    
    public CoreReport01(){
        setId(new Long(1));
        setName("Core Report 01");
        setDescription( 
            "This report is to call out batches that have unusual characteristics "+ 
            "or required unusual handling in a given time period. These batches will "+
            "have comments generated by users and stored within the tracking system."
        );
        List<String> filters = new ArrayList<String>(); 
        filters.add("size");
        filters.add("type");
        setFilters(filters);
        List<String> sorters = new ArrayList<String>(); 
        sorters.add("size");
        sorters.add("type");
        setSorters(sorters);
        setQuery("from gov.loc.repository.packagemodeler.packge.Repository");
        //setParameters(new HashMap());
    }
}
