USE repository;
TRUNCATE packagemodeler_repository;
TRUNCATE algorithmmodeler_fixityalgorithm;
TRUNCATE agentmodeler_agent_role;
TRUNCATE agentmodeler_agent;
TRUNCATE agentmodeler_role;
TRUNCATE externalfilelocationmodeler_mediatype;
TRUNCATE externalidentifiermodeler_identifiertype;

INSERT INTO packagemodeler_repository VALUES (1, 'ndnp');
INSERT INTO algorithmmodeler_fixityalgorithm VALUES (1, 'MD5');
INSERT INTO agentmodeler_role VALUES(1, 'ndnp_awardee');
INSERT INTO agentmodeler_agent VALUES('organization', 1, 'nypl', 'New York Public Library', null, null);
INSERT INTO agentmodeler_agent VALUES('organization', 2, 'loc', 'Library of Congress', null, null);
INSERT INTO agentmodeler_agent_role VALUES(1, 1);
INSERT INTO agentmodeler_agent_role VALUES(2, 1);
INSERT INTO agentmodeler_agent VALUES('person', 3, 'ray', null, 'Ray', 'Murray');
INSERT INTO agentmodeler_agent VALUES('person', 4, 'myron', null, 'Myron', 'Briggs');
INSERT INTO agentmodeler_agent VALUES('person', 5, 'scott', null, 'Scott', 'Phelps');
INSERT INTO agentmodeler_agent VALUES('person', 6, 'brian', null, 'Brian', 'Vargas');
INSERT INTO agentmodeler_agent VALUES('service', 7, 'rdc-jbpm', null, null, null);
INSERT INTO agentmodeler_role VALUES(2, 'storage_service');
INSERT INTO agentmodeler_agent VALUES('service', 8, 'rs25', null, null, null);
INSERT INTO agentmodeler_agent VALUES('service', 9, 'rdc', null, null, null);
INSERT INTO agentmodeler_agent VALUES('service', 10, 'rs15', null, null, null);
INSERT INTO agentmodeler_agent_role VALUES(7, 2);
INSERT INTO agentmodeler_agent_role VALUES(8, 2);
INSERT INTO agentmodeler_agent_role VALUES(9, 2);
INSERT INTO agentmodeler_agent VALUES('software', 11, 'workflow-components-1.0-SNAPSHOT', null, null, null);
INSERT INTO externalfilelocationmodeler_mediatype VALUES(1, 'external harddrive');
INSERT INTO externalidentifiermodeler_identifiertype VALUES(1, 'serial number');
