INSERT INTO core.repository VALUES (1, 'ndnp');
INSERT INTO core.role VALUES(1, 'ndnp_awardee');
INSERT INTO core.agent VALUES('organization', 1, 'nypl', 'New York Public Library', null, null);
INSERT INTO core.agent VALUES('organization', 2, 'loc', 'Library of Congress', null, null);
INSERT INTO core.agent_role VALUES(1, 1);
INSERT INTO core.agent_role VALUES(2, 1);
INSERT INTO core.agent VALUES('person', 3, 'ray', null, 'Ray', 'Murray');
INSERT INTO core.agent VALUES('person', 4, 'myron', null, 'Myron', 'Briggs');
INSERT INTO core.agent VALUES('person', 5, 'scott', null, 'Scott', 'Phelps');
INSERT INTO core.agent VALUES('person', 6, 'brian', null, 'Brian', 'Vargas');
INSERT INTO core.agent VALUES('service', 7, 'rdc-jbpm', null, null, null);
INSERT INTO core.role VALUES(2, 'storage_service');
INSERT INTO core.agent VALUES('service', 8, 'rs25', null, null, null);
INSERT INTO core.agent VALUES('service', 9, 'rdc', null, null, null);
INSERT INTO core.agent VALUES('service', 10, 'rs15', null, null, null);
INSERT INTO core.agent_role VALUES(7, 2);
INSERT INTO core.agent_role VALUES(8, 2);
INSERT INTO core.agent_role VALUES(9, 2);
INSERT INTO core.agent VALUES('software', 11, 'workflow-components-1.0-SNAPSHOT', null, null, null);
