CREATE ROLE package_modeler_role NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;
CREATE ROLE transfer_user WITH PASSWORD 'transfer_user_passwd' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE LOGIN;
GRANT package_modeler_role TO transfer_user;
