create table request_boolean_entries (request_key int8 not null, key varchar(50) not null, value bool);
create table request_integer_entries (request_key int8 not null, key varchar(50) not null, value int8);
create table request_string_entries (request_key int8 not null, key varchar(50) not null, value varchar(255));
create table response_boolean_entries (request_key int8 not null, key varchar(50) not null, value bool);
create table response_integer_entries (request_key int8 not null, key varchar(50) not null, value int8);
create table response_string_entries (request_key int8 not null, key varchar(50) not null, value varchar(255));
create table service_container_registry (host varchar(100) not null, port int4 not null, timestamp timestamp not null, primary key (host));
create table service_request (pkey int8 not null, job_type varchar(50) not null, is_success bool, error_message varchar(255), error_detail text, requester varchar(50) not null, responder varchar(50), correlation_key varchar(255) not null, queue varchar(50) not null, request_date timestamp not null, request_acknowledged_date timestamp, response_date timestamp, response_acknowledged_date timestamp, is_suspended bool not null, primary key (pkey));
alter table request_boolean_entries add constraint FK6D4239C97872DA61 foreign key (request_key) references service_request;
alter table request_integer_entries add constraint FKBF18D8DF7872DA61 foreign key (request_key) references service_request;
alter table request_string_entries add constraint FK4B4916127872DA61 foreign key (request_key) references service_request;
alter table response_boolean_entries add constraint FK4364B77B7872DA61 foreign key (request_key) references service_request;
alter table response_integer_entries add constraint FK953B56917872DA61 foreign key (request_key) references service_request;
alter table response_string_entries add constraint FK28E71A207872DA61 foreign key (request_key) references service_request;
create sequence hibernate_sequence;
